import { memo, useCallback, useMemo, useRef, useState } from 'react';
import {
  ActivityIndicator,
  FlatList,
  KeyboardAvoidingView,
  Modal,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from 'react-native';
import { useFocusEffect, useLocalSearchParams, useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import * as Clipboard from 'expo-clipboard';
import { useProjectsStore } from '../../src/stores/projects';
import { useLanguagesStore } from '../../src/stores/languages';
import { useToastStore } from '../../src/stores/toast';
import { ACTION_META } from '../../src/components/AuthStepsConfig';
import { LanguagePicker } from '../../src/components/LanguagePicker';
import { Badge, Button, Input, EmptyState, AnimatedListItem, AnimatedPressable, LoadingSkeletonList } from '../../src/components/ui';
import { colors, fonts, radius, spacing } from '../../src/theme';
import { formatDateTime, formatUrl } from '../../src/utils/format';
import { AuthStep, Extraction, PageElement } from '../../src/types';

const PAGE_SIZE = 50;

/** Mirrors backend splitWords + ToPascalCase to preview the generated class name */
function toPascalCase(s: string): string {
  return s
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/[_\-]/g, ' ')
    .replace(/[^a-zA-Z0-9 ]/g, ' ')
    .split(/\s+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('');
}

function toSnakeCase(s: string): string {
  return s
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/[_\-]/g, ' ')
    .replace(/[^a-zA-Z0-9 ]/g, ' ')
    .split(/\s+/)
    .filter(Boolean)
    .map((w) => w.toLowerCase())
    .join('_');
}

const LANG_EXT: Record<string, string> = {
  python: '.py',
  java: '.java',
  go: '.go',
  csharp: '.cs',
};

/** Check if an id looks autogenerated (random hashes, MUI _r_ patterns, etc.) */
function isAutoId(id: string): boolean {
  if (!id) return true;
  // MUI: _r_1e_, :r1e:, mui-xxx
  if (/^[_:]r[_:]?\w{1,4}[_:]?$/.test(id)) return true;
  if (/^mui-/i.test(id)) return true;
  // Generic auto-generated: only hex/digits, too short random, uuid-like
  if (/^[0-9a-f-]{8,}$/i.test(id)) return true;
  if (/^[a-z]{1,3}\d{3,}$/i.test(id)) return true;
  return false;
}

/** Get the human-readable label for display */
function displayLabel(el: PageElement): string {
  // Text/label is the most readable
  if (el.text) return el.text.length > 50 ? el.text.slice(0, 50) + '...' : el.text;
  if (el.placeholder) return el.placeholder;
  if (el.name) return el.name;
  if (el.id && !isAutoId(el.id)) return el.id;
  return '';
}

/** Get a subtle secondary hint (the identifier type) */
function secondaryHint(el: PageElement): string {
  if (el.text) {
    if (el.name) return `name="${el.name}"`;
    if (el.id && !isAutoId(el.id)) return `id="${el.id}"`;
  }
  if (el.placeholder && el.name) return `name="${el.name}"`;
  return '';
}

/** Friendly tag display */
function friendlyTag(el: PageElement): string {
  const tag = el.tag;
  if (tag === 'input' && el.type) return `${el.type} input`;
  if (tag === 'textarea') return 'textarea';
  if (tag === 'select') return 'select';
  if (tag === 'button') return 'button';
  if (tag === 'a') return 'link';
  return tag;
}

interface ElementItemProps {
  item: PageElement;
  index: number;
  selected: boolean;
  selectMode: boolean;
  expanded: boolean;
  onToggle: (selector: string) => void;
  onDelete: (selector: string) => void;
  onExpand: (index: number) => void;
  onCopy: (text: string) => void;
}

const ElementItem = memo(function ElementItem({ item, index, selected, selectMode, expanded, onToggle, onDelete, onExpand, onCopy }: ElementItemProps) {
  const label = displayLabel(item);
  const hint = secondaryHint(item);
  const tagLabel = friendlyTag(item);

  return (
    <Pressable
      style={[styles.element, selected && styles.elementSelected]}
      onPress={() => {
        if (selectMode) onToggle(item.selector);
        else onExpand(index);
      }}
    >
      {/* Header: tag badge + label + index */}
      <View style={styles.elementHeader}>
        {selectMode && (
          <Pressable onPress={() => onToggle(item.selector)} hitSlop={8} style={styles.checkboxBtn}>
            <Ionicons
              name={selected ? 'checkbox' : 'square-outline'}
              size={20}
              color={selected ? colors.primary : colors.textTertiary}
            />
          </Pressable>
        )}
        <View style={styles.elementTagBadge}>
          <Text style={styles.elementTagText}>{tagLabel}</Text>
        </View>
        <View style={styles.elementLabelWrap}>
          <Text style={styles.elementLabel} numberOfLines={1}>
            {label || item.selector}
          </Text>
          {hint ? <Text style={styles.elementHint} numberOfLines={1}>{hint}</Text> : null}
        </View>
        <Pressable
          onPress={(e) => { e.stopPropagation(); onCopy(item.selector); }}
          style={styles.copySelectorBtn}
          hitSlop={4}
        >
          <Ionicons name="copy-outline" size={12} color={colors.primary} />
          <Text style={styles.copySelectorText}>Copy selector</Text>
        </Pressable>
        {!selectMode && (
          <Ionicons
            name={expanded ? 'chevron-up' : 'chevron-down'}
            size={14}
            color={colors.textTertiary}
          />
        )}
      </View>

      {/* Selector */}
      <Text style={styles.selector} numberOfLines={1}>{item.selector}</Text>

      {/* Expanded details */}
      {expanded && (
        <View style={styles.elementExpanded}>
          {item.id ? <Text style={styles.elementAttr}>id: {item.id}</Text> : null}
          {item.name ? <Text style={styles.elementAttr}>name: {item.name}</Text> : null}
          {item.text ? (
            <Text style={styles.elementAttr} numberOfLines={2}>text: {item.text}</Text>
          ) : null}
          {item.placeholder ? (
            <Text style={styles.elementAttr}>placeholder: {item.placeholder}</Text>
          ) : null}
          {item.href ? (
            <Text style={styles.elementAttr} numberOfLines={1}>href: {item.href}</Text>
          ) : null}
          {item.class ? (
            <Text style={styles.elementAttr} numberOfLines={1}>class: {item.class}</Text>
          ) : null}
          {!selectMode && (
            <Pressable onPress={() => onDelete(item.selector)} style={styles.elementDeleteBtn}>
              <Ionicons name="trash-outline" size={14} color={colors.danger} />
              <Text style={styles.elementDeleteText}>Remove element</Text>
            </Pressable>
          )}
        </View>
      )}
    </Pressable>
  );
});

export default function ExtractionDetailScreen() {
  const { id, projectId } = useLocalSearchParams<{ id: string; projectId: string }>();
  const router = useRouter();
  const store = useProjectsStore();
  const languages = useLanguagesStore((s) => s.languages);
  const toast = useToastStore((s) => s.show);
  const insets = useSafeAreaInsets();

  const [extraction, setExtraction] = useState<Extraction | null>(null);
  const [loading, setLoading] = useState(true);

  // Editable title
  const [editingTitle, setEditingTitle] = useState(false);
  const [titleDraft, setTitleDraft] = useState('');
  const [savingTitle, setSavingTitle] = useState(false);
  const savingTitleRef = useRef(false);

  // Select mode for bulk delete
  const [selectMode, setSelectMode] = useState(false);
  const [selected, setSelected] = useState<Set<string>>(new Set());

  // Expanded elements
  const [expandedElements, setExpandedElements] = useState<Set<number>>(new Set());

  // Filter
  const [filterText, setFilterText] = useState('');

  // Local pagination for elements
  const [visibleCount, setVisibleCount] = useState(PAGE_SIZE);

  // Generate modal
  const [showGenerate, setShowGenerate] = useState(false);
  const [languageId, setLanguageId] = useState('');
  const [pageName, setPageName] = useState('');
  const [generating, setGenerating] = useState(false);
  const [genError, setGenError] = useState('');

  // Pre-steps collapsible
  const [preStepsOpen, setPreStepsOpen] = useState(false);

  // Analyze state
  const [analyzing, setAnalyzing] = useState(false);

  const loadExtraction = useCallback(() => {
    if (!id || !projectId) return;
    store
      .getExtraction(projectId, id)
      .then((ext) => {
        setExtraction(ext);
        setVisibleCount(PAGE_SIZE);
      })
      .catch((err: any) => {
        toast('error', err?.response?.data?.error || 'Failed to load extraction');
      })
      .finally(() => setLoading(false));
  }, [id, projectId, store, toast]);

  useFocusEffect(
    useCallback(() => {
      loadExtraction();
    }, [loadExtraction])
  );

  // ── Title edit ──

  const handleStartEditTitle = () => {
    setTitleDraft(extraction?.page_title || '');
    setEditingTitle(true);
  };

  const handleSaveTitle = async () => {
    if (savingTitleRef.current) return;
    const trimmed = titleDraft.trim();
    if (!trimmed || trimmed === extraction?.page_title) {
      setEditingTitle(false);
      return;
    }
    savingTitleRef.current = true;
    setSavingTitle(true);
    try {
      await store.updateExtractionTitle(projectId!, id!, trimmed);
      setExtraction((prev) => prev ? { ...prev, page_title: trimmed } : prev);
      toast('success', 'Title updated');
    } catch (err: any) {
      toast('error', err?.response?.data?.error || 'Failed to update title');
    } finally {
      savingTitleRef.current = false;
      setSavingTitle(false);
      setEditingTitle(false);
    }
  };

  // ── Delete extraction ──

  const handleDeleteExtraction = () => {
    const doDelete = async () => {
      try {
        await store.deleteExtraction(projectId!, id!);
        toast('success', 'Extraction deleted');
        router.canGoBack() ? router.back() : router.replace(`/project/${projectId}`);
      } catch (err: any) {
        toast('error', err?.response?.data?.error || 'Failed to delete extraction');
      }
    };

    if (Platform.OS === 'web') {
      if (!window.confirm('Delete this extraction? This cannot be undone.')) return;
      doDelete();
    } else {
      const { Alert } = require('react-native');
      Alert.alert('Delete Extraction', 'This will permanently delete this extraction.', [
        { text: 'Cancel', style: 'cancel' },
        { text: 'Delete', style: 'destructive', onPress: doDelete },
      ]);
    }
  };

  // ── Delete single element ──

  const handleDeleteSingleElement = (selector: string) => {
    const doDelete = async () => {
      try {
        const remaining = await store.deleteElements(projectId!, id!, [selector]);
        setExtraction((prev) => {
          if (!prev) return prev;
          const updated = (prev.elements_json || []).filter((el) => el.selector !== selector);
          return { ...prev, elements_json: updated, element_count: remaining };
        });
        toast('success', 'Element removed');
      } catch (err: any) {
        toast('error', err?.response?.data?.error || 'Failed to delete element');
      }
    };

    if (Platform.OS === 'web') {
      if (!window.confirm(`Remove element "${selector}"?`)) return;
      doDelete();
    } else {
      const { Alert } = require('react-native');
      Alert.alert('Remove Element', `Remove "${selector}"?`, [
        { text: 'Cancel', style: 'cancel' },
        { text: 'Remove', style: 'destructive', onPress: doDelete },
      ]);
    }
  };

  // ── Bulk delete ──

  const handleToggleSelect = (selector: string) => {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(selector)) next.delete(selector);
      else next.add(selector);
      return next;
    });
  };

  const handleSelectAll = () => {
    const allSelectors = (extraction?.elements_json || []).map((el) => el.selector);
    if (selected.size === allSelectors.length) {
      setSelected(new Set());
    } else {
      setSelected(new Set(allSelectors));
    }
  };

  const handleBulkDelete = () => {
    if (selected.size === 0) return;

    const doDelete = async () => {
      try {
        const selectors = Array.from(selected);
        const remaining = await store.deleteElements(projectId!, id!, selectors);
        setExtraction((prev) => {
          if (!prev) return prev;
          const updated = (prev.elements_json || []).filter((el) => !selected.has(el.selector));
          return { ...prev, elements_json: updated, element_count: remaining };
        });
        toast('success', `${selectors.length} element(s) removed`);
        setSelected(new Set());
        setSelectMode(false);
      } catch (err: any) {
        toast('error', err?.response?.data?.error || 'Failed to delete elements');
      }
    };

    if (Platform.OS === 'web') {
      if (!window.confirm(`Delete ${selected.size} selected element(s)?`)) return;
      doDelete();
    } else {
      const { Alert } = require('react-native');
      Alert.alert('Delete Elements', `Remove ${selected.size} selected element(s)?`, [
        { text: 'Cancel', style: 'cancel' },
        { text: 'Delete', style: 'destructive', onPress: doDelete },
      ]);
    }
  };

  const handleCancelSelect = () => {
    setSelectMode(false);
    setSelected(new Set());
  };

  // ── Expand element ──

  const handleExpandElement = useCallback((index: number) => {
    setExpandedElements((prev) => {
      const next = new Set(prev);
      if (next.has(index)) next.delete(index);
      else next.add(index);
      return next;
    });
  }, []);

  // ── Generate ──

  const handleGenerate = async () => {
    setGenError('');
    if (!languageId) {
      setGenError('Select a language');
      return;
    }
    setGenerating(true);
    try {
      const genId = await store.generatePom(id!, projectId!, languageId, pageName.trim() || undefined);
      setShowGenerate(false);
      toast('success', 'POM generated successfully');
      router.push(`/generation/${genId}?projectId=${projectId}`);
    } catch (err: any) {
      setGenError(err?.response?.data?.error || 'Generation failed');
    } finally {
      setGenerating(false);
    }
  };

  // ── Analyze ──

  const handleAnalyze = async () => {
    setAnalyzing(true);
    try {
      const analysisId = await store.analyzePage(id!, projectId!);
      toast('success', 'Analysis completed');
      router.push(`/analysis/${analysisId}?projectId=${projectId}`);
    } catch (err: any) {
      if (err?.response?.status === 402) {
        toast('warning', 'AI Analysis requires API key (premium)');
      } else {
        toast('error', err?.response?.data?.error || 'Analysis failed');
      }
    } finally {
      setAnalyzing(false);
    }
  };

  // ── Filter + local pagination ──

  const allElements = extraction?.elements_json || [];

  const filteredElements = useMemo(() => {
    if (!filterText.trim()) return allElements;
    const q = filterText.toLowerCase();
    return allElements.filter((el) =>
      el.tag.toLowerCase().includes(q) ||
      (el.id && el.id.toLowerCase().includes(q)) ||
      (el.name && el.name.toLowerCase().includes(q)) ||
      (el.selector && el.selector.toLowerCase().includes(q)) ||
      (el.text && el.text.toLowerCase().includes(q)) ||
      (el.type && el.type.toLowerCase().includes(q)) ||
      (el.placeholder && el.placeholder.toLowerCase().includes(q))
    );
  }, [allElements, filterText]);

  const visibleElements = filteredElements.slice(0, visibleCount);
  const hasMoreElements = visibleCount < filteredElements.length;

  const handleCopySelector = useCallback(async (text: string) => {
    try {
      await Clipboard.setStringAsync(text);
      toast('success', 'Selector copied');
    } catch {
      toast('error', 'Failed to copy');
    }
  }, [toast]);

  const handleLoadMoreElements = () => {
    if (hasMoreElements) {
      setVisibleCount((prev) => Math.min(prev + PAGE_SIZE, filteredElements.length));
    }
  };

  // ── Render ──

  if (loading) {
    return (
      <View style={styles.container}>
        <View style={[styles.header, { paddingTop: insets.top + spacing.sm }]}>
          <Pressable onPress={() => router.canGoBack() ? router.back() : router.replace(`/project/${projectId}`)} style={styles.backBtn}>
            <Ionicons name="arrow-back" size={24} color={colors.text} />
          </Pressable>
          <View style={styles.headerCenter}>
            <Text style={styles.headerTitle}>Loading...</Text>
          </View>
        </View>
        <LoadingSkeletonList count={5} />
      </View>
    );
  }

  if (!extraction) return <EmptyState title="Extraction not found" />;

  return (
    <View style={styles.container}>
      {/* Header */}
      <View style={[styles.header, { paddingTop: insets.top + spacing.sm }]}>
        <Pressable onPress={() => router.canGoBack() ? router.back() : router.replace(`/project/${projectId}`)} style={styles.backBtn}>
          <Ionicons name="arrow-back" size={24} color={colors.text} />
        </Pressable>
        <View style={styles.headerCenter}>
          {editingTitle ? (
            <View style={styles.titleEditRow}>
              <TextInput
                style={styles.titleInput}
                value={titleDraft}
                onChangeText={setTitleDraft}
                onBlur={handleSaveTitle}
                onSubmitEditing={handleSaveTitle}
                autoFocus
                selectTextOnFocus
                returnKeyType="done"
              />
              {savingTitle && <ActivityIndicator size="small" color={colors.primary} />}
            </View>
          ) : (
            <Pressable onPress={handleStartEditTitle} style={styles.titleRow}>
              <Text style={styles.headerTitle} numberOfLines={1}>
                {extraction.page_title || 'Extraction'}
              </Text>
              <Ionicons name="pencil-outline" size={16} color={colors.textTertiary} />
            </Pressable>
          )}
        </View>
        <Pressable onPress={handleDeleteExtraction} hitSlop={8}>
          <Ionicons name="trash-outline" size={22} color={colors.danger} />
        </Pressable>
      </View>

      {/* Compact Info + Actions merged */}
      <View style={styles.infoBlock}>
        {/* Row 1: Status + date + element count */}
        <View style={styles.infoTopRow}>
          <Badge
            text={extraction.status}
            variant={extraction.status === 'completed' ? 'success' : extraction.status === 'failed' ? 'danger' : 'warning'}
          />
          <Text style={styles.meta}>{formatDateTime(extraction.created_at)}</Text>
          <Text style={styles.countBadge}>{extraction.element_count} el.</Text>
        </View>

        {/* URL */}
        <Text style={styles.url} numberOfLines={1}>{formatUrl(extraction.url)}</Text>

        {/* Pre-steps + action buttons row */}
        <View style={styles.infoActionsRow}>
          {extraction.pre_steps && extraction.pre_steps.length > 0 && (
            <Pressable
              style={styles.preStepsBadge}
              onPress={() => setPreStepsOpen((v) => !v)}
            >
              <Ionicons name="list-outline" size={13} color={colors.primary} />
              <Text style={styles.preStepsBadgeText}>
                {extraction.pre_steps.length} pre-steps
              </Text>
              <Ionicons
                name={preStepsOpen ? 'chevron-up' : 'chevron-down'}
                size={12}
                color={colors.textTertiary}
              />
            </Pressable>
          )}
          <View style={{ flex: 1 }} />
          <Pressable
            style={styles.analyzeBtn}
            onPress={handleAnalyze}
            disabled={analyzing}
          >
            {analyzing ? (
              <ActivityIndicator size="small" color={colors.info} />
            ) : (
              <>
                <Ionicons name="sparkles-outline" size={14} color={colors.info} />
                <Text style={styles.analyzeBtnText}>Analyze</Text>
              </>
            )}
          </Pressable>
        </View>

        {/* Pre-steps expanded list with ACTION_META colors */}
        {preStepsOpen && extraction.pre_steps && extraction.pre_steps.length > 0 && (
          <View style={styles.preStepsList}>
            {extraction.pre_steps.map((step: AuthStep, i: number) => {
              const meta = ACTION_META[step.action] || ACTION_META.wait;
              return (
                <View key={i} style={styles.preStepItem}>
                  <Text style={styles.preStepIndex}>{i + 1}</Text>
                  <View style={[styles.preStepActionBadge, { backgroundColor: meta.bg }]}>
                    <Ionicons name={meta.icon as any} size={12} color={meta.color} />
                    <Text style={[styles.preStepActionText, { color: meta.color }]}>{step.action}</Text>
                  </View>
                  <Text style={styles.preStepDetail} numberOfLines={1}>
                    {step.url || step.selector || step.for || ''}
                  </Text>
                </View>
              );
            })}
          </View>
        )}
      </View>

      {/* Select mode toolbar */}
      {selectMode ? (
        <View style={styles.selectToolbar}>
          <Pressable onPress={handleSelectAll} style={styles.selectAction}>
            <Ionicons
              name={selected.size === allElements.length ? 'checkbox' : 'square-outline'}
              size={20}
              color={colors.primary}
            />
            <Text style={styles.selectActionText}>
              {selected.size === allElements.length ? 'Deselect all' : 'Select all'}
            </Text>
          </Pressable>
          <Text style={styles.selectCount}>{selected.size} selected</Text>
          <View style={styles.selectActions}>
            <Pressable onPress={handleCancelSelect} style={styles.selectAction}>
              <Text style={styles.cancelText}>Cancel</Text>
            </Pressable>
            <Pressable onPress={handleBulkDelete} style={[styles.selectAction, selected.size === 0 && { opacity: 0.4 }]}>
              <Ionicons name="trash-outline" size={18} color={colors.danger} />
              <Text style={styles.deleteText}>Delete</Text>
            </Pressable>
          </View>
        </View>
      ) : null}

      {/* Elements List */}
      <FlatList
        data={visibleElements}
        keyExtractor={(item, index) => `${item.selector}-${index}`}
        keyboardDismissMode="on-drag"
        keyboardShouldPersistTaps="handled"
        renderItem={({ item, index }) => (
          <AnimatedListItem index={Math.min(index, 10)}>
            <ElementItem
              item={item}
              index={index}
              selected={selected.has(item.selector)}
              selectMode={selectMode}
              expanded={expandedElements.has(index)}
              onToggle={handleToggleSelect}
              onDelete={handleDeleteSingleElement}
              onExpand={handleExpandElement}
              onCopy={handleCopySelector}
            />
          </AnimatedListItem>
        )}
        contentContainerStyle={[styles.list, { paddingBottom: spacing.xxl + 60 }]}
        ListHeaderComponent={
          <View>
            <View style={styles.listHeaderRow}>
              <Text style={styles.sectionTitle}>
                Page Elements{filterText.trim() ? ` (${filteredElements.length})` : ''}
              </Text>
              {allElements.length > 0 && !selectMode && (
                <Pressable onPress={() => setSelectMode(true)} style={styles.selectModeBtn}>
                  <Ionicons name="checkmark-done-outline" size={18} color={colors.textSecondary} />
                  <Text style={styles.selectModeText}>Select</Text>
                </Pressable>
              )}
            </View>
            {/* Filter bar */}
            {allElements.length > 3 && (
              <View style={styles.filterBar}>
                <Ionicons name="search-outline" size={16} color={colors.textTertiary} />
                <TextInput
                  style={styles.filterInput}
                  value={filterText}
                  onChangeText={(v) => {
                    setFilterText(v);
                    setVisibleCount(PAGE_SIZE);
                  }}
                  placeholder="Filter by tag, id, name, selector..."
                  placeholderTextColor={colors.textTertiary}
                  autoCapitalize="none"
                  autoCorrect={false}
                />
                {filterText.length > 0 && (
                  <Pressable onPress={() => setFilterText('')} hitSlop={8}>
                    <Ionicons name="close-circle" size={16} color={colors.textTertiary} />
                  </Pressable>
                )}
              </View>
            )}
          </View>
        }
        ListFooterComponent={
          hasMoreElements ? (
            <Pressable onPress={handleLoadMoreElements} style={styles.loadMoreBtn}>
              <Text style={styles.loadMoreText}>
                Show more ({filteredElements.length - visibleCount} remaining)
              </Text>
            </Pressable>
          ) : null
        }
        ListEmptyComponent={
          filterText.trim() ? (
            <EmptyState icon="search-outline" title="No matches" subtitle={`No elements match "${filterText}"`} />
          ) : (
            <EmptyState icon="code-outline" title="No elements" subtitle="No interactive elements were found" />
          )
        }
        onEndReached={handleLoadMoreElements}
        onEndReachedThreshold={0.3}
      />

      {/* FAB - Generate POM */}
      <AnimatedPressable
        style={[styles.fab, { bottom: insets.bottom + spacing.md }]}
        onPress={() => {
          setPageName(extraction.page_title || '');
          setShowGenerate(true);
        }}
      >
        <Ionicons name="code-slash-outline" size={22} color={colors.bg} />
        <Text style={styles.fabText}>Generate POM</Text>
      </AnimatedPressable>

      {/* Generate Modal */}
      <Modal visible={showGenerate} animationType="slide" transparent>
        <KeyboardAvoidingView
          behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
          style={styles.modalOverlay}
        >
          <View style={styles.modal}>
            <View style={styles.modalHeaderRow}>
              <Text style={styles.modalTitle}>Generate POM</Text>
              <Pressable onPress={() => setShowGenerate(false)}>
                <Ionicons name="close" size={24} color={colors.textSecondary} />
              </Pressable>
            </View>
            <ScrollView
              keyboardShouldPersistTaps="handled"
              showsVerticalScrollIndicator={false}
            >
              <Text style={styles.modalSubtitle}>
                Generate Page Object Model and test code using AI
              </Text>
              <Input
                label="Page Name"
                value={pageName}
                onChangeText={setPageName}
                placeholder="LoginPage"
              />
              {pageName.trim() ? (() => {
                const lang = languages.find((l) => l.id === languageId);
                const ext = lang ? (LANG_EXT[lang.name] || '') : '';
                const usePascalFile = lang && (lang.name === 'java' || lang.name === 'csharp');
                const fileName = usePascalFile ? toPascalCase(pageName) : toSnakeCase(pageName);
                return (
                  <View style={styles.namePreview}>
                    <Text style={styles.previewLabel}>Class:</Text>
                    <Text style={styles.previewValue}>{toPascalCase(pageName)}</Text>
                    <Text style={styles.previewLabel}>File:</Text>
                    <Text style={styles.previewValue}>{fileName}{ext}</Text>
                  </View>
                );
              })() : null}
              <LanguagePicker selectedId={languageId} onSelect={setLanguageId} />
              {genError ? <Text style={styles.error}>{genError}</Text> : null}
            </ScrollView>
            <View style={styles.modalActions}>
              <Button title="Cancel" variant="secondary" onPress={() => setShowGenerate(false)} />
              <Button title="Generate" onPress={handleGenerate} loading={generating} />
            </View>
          </View>
        </KeyboardAvoidingView>
      </Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingTop: spacing.xxl,
    paddingBottom: spacing.md,
    backgroundColor: colors.bgSecondary,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backBtn: {
    padding: spacing.xs,
    marginRight: spacing.sm,
  },
  headerCenter: {
    flex: 1,
  },
  headerTitle: {
    color: colors.text,
    fontSize: fonts.sizes.lg,
    fontWeight: '600',
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  titleEditRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  titleInput: {
    flex: 1,
    color: colors.text,
    fontSize: fonts.sizes.lg,
    fontWeight: '600',
    borderBottomWidth: 2,
    borderBottomColor: colors.primary,
    paddingVertical: 2,
    paddingHorizontal: 0,
  },

  // Compact info block (merged info + actions)
  infoBlock: {
    padding: spacing.md,
    paddingBottom: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  infoTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.xs,
  },
  meta: {
    color: colors.textTertiary,
    fontSize: fonts.sizes.xs,
    flex: 1,
  },
  countBadge: {
    color: colors.textSecondary,
    fontSize: fonts.sizes.xs,
    fontWeight: '600',
    backgroundColor: colors.bgTertiary,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: radius.sm,
    overflow: 'hidden',
  },
  url: {
    color: colors.textTertiary,
    fontSize: fonts.sizes.xs,
    fontFamily: 'monospace',
    marginBottom: spacing.sm,
  },
  infoActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  analyzeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.bgTertiary,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
  },
  analyzeBtnText: {
    color: colors.info,
    fontSize: fonts.sizes.xs,
    fontWeight: '600',
  },

  // Pre-steps
  preStepsBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    alignSelf: 'flex-start',
    backgroundColor: colors.primaryDark + '20',
    borderWidth: 1,
    borderColor: colors.primary + '40',
    borderRadius: radius.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
  },
  preStepsBadgeText: {
    color: colors.primary,
    fontSize: fonts.sizes.xs,
    fontWeight: '600',
  },
  preStepsList: {
    marginTop: spacing.sm,
    backgroundColor: colors.bg,
    borderRadius: radius.sm,
    padding: spacing.sm,
  },
  preStepItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingVertical: 4,
  },
  preStepIndex: {
    color: colors.textTertiary,
    fontSize: 10,
    fontFamily: 'monospace',
    width: 16,
    textAlign: 'right',
  },
  preStepActionBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  preStepActionText: {
    fontSize: 10,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  preStepDetail: {
    flex: 1,
    color: colors.textTertiary,
    fontSize: 11,
    fontFamily: 'monospace',
  },

  // Select toolbar
  selectToolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.bgSecondary,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: spacing.sm,
  },
  selectAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  selectActionText: {
    color: colors.primary,
    fontSize: fonts.sizes.sm,
    fontWeight: '500',
  },
  selectCount: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: fonts.sizes.sm,
    textAlign: 'center',
  },
  selectActions: {
    flexDirection: 'row',
    gap: spacing.md,
  },
  cancelText: {
    color: colors.textSecondary,
    fontSize: fonts.sizes.sm,
    fontWeight: '500',
  },
  deleteText: {
    color: colors.danger,
    fontSize: fonts.sizes.sm,
    fontWeight: '500',
  },

  // List header
  listHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: fonts.sizes.md,
    fontWeight: '600',
  },
  selectModeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  selectModeText: {
    color: colors.textSecondary,
    fontSize: fonts.sizes.sm,
  },

  // Filter bar
  filterBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    backgroundColor: colors.bgSecondary,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.sm,
    marginBottom: spacing.sm,
    minHeight: 40,
  },
  filterInput: {
    flex: 1,
    color: colors.text,
    fontSize: fonts.sizes.sm,
    paddingVertical: spacing.xs,
  },

  // List
  list: {
    padding: spacing.md,
    paddingBottom: spacing.xxl,
  },

  // Element cards (condensed)
  element: {
    backgroundColor: colors.bgSecondary,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing.sm,
    marginBottom: spacing.sm,
  },
  elementSelected: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryDark + '15',
  },
  elementHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  checkboxBtn: {
    marginRight: 2,
  },
  elementTagBadge: {
    backgroundColor: colors.bgTertiary,
    borderRadius: radius.sm,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  elementTagText: {
    color: colors.primary,
    fontSize: 11,
    fontFamily: 'monospace',
    fontWeight: '600',
  },
  elementLabelWrap: {
    flex: 1,
    gap: 2,
  },
  elementLabel: {
    color: colors.text,
    fontSize: fonts.sizes.sm,
    fontWeight: '500',
  },
  elementHint: {
    color: colors.textTertiary,
    fontSize: fonts.sizes.xs,
    fontFamily: 'monospace',
  },
  elementIndex: {
    color: colors.textTertiary,
    fontSize: fonts.sizes.xs,
  },
  selector: {
    color: colors.textTertiary,
    fontSize: 11,
    fontFamily: 'monospace',
    marginTop: 4,
  },
  copySelectorBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: `${colors.primary}18`,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: `${colors.primary}30`,
  },
  copySelectorText: {
    fontSize: 11,
    color: colors.primary,
    fontFamily: fonts.regular,
  },
  elementExpanded: {
    marginTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: spacing.sm,
  },
  elementAttr: {
    color: colors.textSecondary,
    fontSize: fonts.sizes.xs,
    fontFamily: 'monospace',
    marginBottom: 2,
  },
  elementDeleteBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    marginTop: spacing.sm,
    paddingVertical: 6,
    backgroundColor: colors.danger + '15',
    borderRadius: radius.sm,
  },
  elementDeleteText: {
    color: colors.danger,
    fontSize: fonts.sizes.xs,
    fontWeight: '500',
  },

  // Load more
  loadMoreBtn: {
    alignItems: 'center',
    paddingVertical: spacing.md,
  },
  loadMoreText: {
    color: colors.primary,
    fontSize: fonts.sizes.sm,
    fontWeight: '500',
  },

  // FAB
  fab: {
    position: 'absolute',
    right: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    backgroundColor: colors.primary,
    borderRadius: radius.full,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 4,
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
  },
  fabText: {
    color: colors.bg,
    fontSize: fonts.sizes.sm,
    fontWeight: '700',
  },

  // Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-end',
  },
  modal: {
    backgroundColor: colors.bgSecondary,
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    padding: spacing.lg,
  },
  modalHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  modalTitle: {
    color: colors.text,
    fontSize: fonts.sizes.xl,
    fontWeight: '700',
  },
  modalSubtitle: {
    color: colors.textSecondary,
    fontSize: fonts.sizes.sm,
    marginBottom: spacing.lg,
  },
  namePreview: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: colors.bg,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    marginBottom: spacing.sm,
  },
  previewLabel: {
    color: colors.textTertiary,
    fontSize: fonts.sizes.xs,
    fontWeight: '600',
  },
  previewValue: {
    color: colors.primary,
    fontSize: fonts.sizes.xs,
    fontFamily: 'monospace',
  },
  error: {
    color: colors.danger,
    fontSize: fonts.sizes.sm,
    marginBottom: spacing.md,
    textAlign: 'center',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
});
