// Framework scaffold content generators (mirrors backend scaffold.go)

export function getInstallScript(lang: string, projectName: string): string {
  switch (lang.toLowerCase()) {
    case 'python':
      return `#!/bin/bash
# Install script for ${projectName}
# Generated by pom-app

set -e

echo "Setting up Python Playwright project..."

# Create virtual environment
python3 -m venv venv
source venv/bin/activate

# Install dependencies
pip install -r requirements.txt

# Install Playwright browsers
playwright install chromium

echo ""
echo "Setup complete!"
echo "Activate virtual environment: source venv/bin/activate"
echo "Run tests: pytest"`;

    case 'java':
      return `#!/bin/bash
# Install script for ${projectName}
# Generated by pom-app

set -e

echo "Setting up Java Selenium project..."

# Build with Maven and download dependencies
mvn clean install -DskipTests

echo ""
echo "Setup complete!"
echo "Run tests: mvn test"`;

    default:
      return `#!/bin/bash
# Install script for ${projectName}
# Generated by pom-app

echo "Please install dependencies manually for this project."`;
  }
}

export function getGitignore(lang: string): string {
  const common = `# IDE
.idea/
.vscode/
*.swp
*.swo

# Environment
.env
.env.local

# OS
.DS_Store
Thumbs.db

# Test output
screenshots/
allure-results/
allure-report/`;

  switch (lang.toLowerCase()) {
    case 'python':
      return common + `

# Python
__pycache__/
*.py[cod]
*$py.class
*.egg-info/
dist/
build/
venv/
.venv/
.pytest_cache/
htmlcov/
.coverage`;

    case 'java':
      return common + `

# Java
target/
*.class
*.jar
*.war
*.ear
*.iml
.settings/
.project
.classpath`;

    default:
      return common;
  }
}

export function getReadme(projectName: string, lang: string, framework: string): string {
  const langDisplay: Record<string, string> = {
    python: 'Python', java: 'Java',
  };
  const runners: Record<string, string> = {
    python: 'pytest', java: 'TestNG',
  };
  const runCmds: Record<string, string> = {
    python: 'source venv/bin/activate\npytest --alluredir=allure-results',
    java: 'mvn test',
  };

  const l = lang.toLowerCase();
  return `# ${projectName}

> Generated by [pom-app](https://github.com/pom-app)

## Tech Stack

- **Language**: ${langDisplay[l] || lang}
- **Framework**: ${framework.charAt(0).toUpperCase() + framework.slice(1)}
- **Test Runner**: ${runners[l] || 'unknown'}
- **Reporting**: Allure

## Quick Start

\`\`\`bash
chmod +x install.sh
./install.sh
\`\`\`

## Run Tests

\`\`\`bash
${runCmds[l] || '# run tests manually'}
\`\`\``;
}

export function getProjectTree(lang: string): string {
  switch (lang.toLowerCase()) {
    case 'python':
      return `├── requirements.txt
├── pytest.ini
├── behave.ini
├── install.sh
├── .gitignore
├── README.md
├── pages/
│   ├── base_page.py
│   └── *.py
├── tests/
│   └── test_*.py
├── features/
│   ├── environment.py
│   ├── steps/
│   │   └── common_steps.py
│   └── *.feature
└── analysis/
    └── *_analysis.md`;

    case 'java':
      return `├── pom.xml
├── testng.xml
├── install.sh
├── .gitignore
├── README.md
└── src/test/
    ├── java/
    │   ├── base/
    │   │   ├── BasePage.java
    │   │   └── BaseTest.java
    │   ├── pages/
    │   │   └── *.java
    │   ├── tests/
    │   │   └── *Test.java
    │   ├── steps/
    │   │   ├── Hooks.java
    │   │   └── CommonSteps.java
    │   └── analysis/
    │       └── *_analysis.md
    └── resources/
        └── features/
            └── *.feature`;

    default:
      return `├── install.sh
├── .gitignore
├── README.md
├── pages/
├── tests/
├── features/
└── analysis/`;
  }
}

export function getRunCommand(lang: string): string {
  switch (lang.toLowerCase()) {
    case 'python': return 'pytest';
    case 'java': return 'mvn test';
    default: return '';
  }
}

// ── BDD Framework Helpers ──

export interface BddFrameworkInfo {
  name: string;        // e.g. "Behave"
  runner: string;      // e.g. "behave"
  configFile: string;  // e.g. "behave.ini"
  stepsDir: string;    // e.g. "features/steps/"
  hooksFile: string;   // e.g. "features/environment.py"
  featureDir: string;  // e.g. "features/"
}

const BDD_FRAMEWORKS: Record<string, BddFrameworkInfo> = {
  python: {
    name: 'Behave',
    runner: 'behave',
    configFile: 'behave.ini',
    stepsDir: 'features/steps/',
    hooksFile: 'features/environment.py',
    featureDir: 'features/',
  },
  java: {
    name: 'Cucumber',
    runner: 'mvn test -Dcucumber',
    configFile: 'pom.xml (cucumber deps)',
    stepsDir: 'src/test/java/steps/',
    hooksFile: 'src/test/java/steps/Hooks.java',
    featureDir: 'src/test/resources/features/',
  },
};

export function getBddFrameworkInfo(lang: string): BddFrameworkInfo | null {
  return BDD_FRAMEWORKS[lang.toLowerCase()] || null;
}

export function getBddRunCommand(lang: string): string {
  const info = getBddFrameworkInfo(lang);
  return info ? info.runner : '';
}

export function getBddConfigPreview(lang: string): string {
  switch (lang.toLowerCase()) {
    case 'python':
      return `[behave]
paths = features/
format = allure_behave.formatter:AllureFormatter
outfiles = allure-results/

[behave.userdata]
browser = chromium
headless = true`;

    case 'java':
      return `<!-- Cucumber dependencies in pom.xml -->
<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-java</artifactId>
    <version>7.15.0</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-testng</artifactId>
    <version>7.15.0</version>
    <scope>test</scope>
</dependency>`;

    default:
      return '';
  }
}

export function getBddStepsPreview(lang: string): string {
  switch (lang.toLowerCase()) {
    case 'python':
      return `from behave import given, when, then
from pages.base_page import BasePage


@given('I am on the "{page_name}" page')
def step_navigate_to_page(context, page_name):
    context.page.goto(context.base_url)


@when('I fill "{field}" with "{value}"')
def step_fill_field(context, field, value):
    context.page.fill(f'[name="{field}"]', value)


@when('I click the "{button}" button')
def step_click_button(context, button):
    context.page.click(f'text={button}')


@then('I should see "{text}"')
def step_should_see_text(context, text):
    assert context.page.is_visible(f'text={text}')`;

    case 'java':
      return `import io.cucumber.java.en.*;
import com.microsoft.playwright.*;
import static org.testng.Assert.*;

public class CommonSteps {
    private Page page;

    @Given("I am on the {string} page")
    public void navigateToPage(String pageName) {
        page.navigate(System.getenv("BASE_URL"));
    }

    @When("I fill {string} with {string}")
    public void fillField(String field, String value) {
        page.fill("[name=\\"" + field + "\\"]", value);
    }

    @When("I click the {string} button")
    public void clickButton(String button) {
        page.click("text=" + button);
    }

    @Then("I should see {string}")
    public void shouldSeeText(String text) {
        assertTrue(page.isVisible("text=" + text));
    }
}`;

    default:
      return '';
  }
}

// ── API Scaffold Helpers (mirrors api_scaffold.go) ──

export function getApiProjectTree(lang: string): string {
  switch (lang.toLowerCase()) {
    case 'python':
      return `├── requirements.txt
├── pytest.ini
├── .env.example
├── .gitignore
├── install.sh
├── Dockerfile
├── README.md
├── .github/
│   └── workflows/
│       └── tests.yml
├── api/
│   ├── __init__.py
│   ├── base_client.py
│   └── endpoints/
│       ├── __init__.py
│       └── *.py
└── tests/
    ├── __init__.py
    ├── conftest.py
    └── test_*.py`;

    case 'java':
      return `├── pom.xml
├── testng.xml
├── .env.example
├── .gitignore
├── install.sh
├── Dockerfile
├── README.md
├── .github/
│   └── workflows/
│       └── tests.yml
└── src/
    ├── main/java/api/
    │   ├── BaseApiClient.java
    │   └── endpoints/
    │       └── *Api.java
    └── test/java/
        ├── base/
        │   └── BaseApiTest.java
        └── tests/
            └── *Test.java`;

    default:
      return `├── .env.example
├── .gitignore
├── install.sh
├── Dockerfile
├── README.md
├── api/
└── tests/`;
  }
}

export function getApiInstallScript(lang: string, projectName: string): string {
  switch (lang.toLowerCase()) {
    case 'python':
      return `#!/bin/bash
# Install script for ${projectName}
set -e

echo "Setting up Python API testing project..."
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt

echo ""
echo "Setup complete!"
echo "1. Copy .env.example to .env and set your variables"
echo "2. Run tests: pytest"`;

    case 'java':
      return `#!/bin/bash
# Install script for ${projectName}
set -e

echo "Setting up Java API testing project..."
mvn clean install -DskipTests

echo ""
echo "Setup complete!"
echo "1. Copy .env.example to .env and set your variables"
echo "2. Run tests: mvn test"`;

    default:
      return `#!/bin/bash
# Install script for ${projectName}
set -e

echo "Please install dependencies manually for this project."`;
  }
}

export function getApiReadme(projectName: string, lang: string, endpoints: { method: string; path: string; name: string; expected_status: number }[]): string {
  const l = lang.toLowerCase();
  const langInfo: Record<string, { lang: string; client: string; runner: string; runCmd: string }> = {
    python: { lang: 'Python', client: 'requests', runner: 'pytest', runCmd: 'source venv/bin/activate\npytest' },
    java: { lang: 'Java 17', client: 'REST Assured', runner: 'TestNG', runCmd: 'mvn test' },
  };
  const info = langInfo[l] || { lang: lang, client: 'HTTP', runner: 'unknown', runCmd: '# run tests' };

  const endpointsTable = endpoints.length > 0
    ? endpoints.map((e) => `| ${e.method} | ${e.path} | ${e.name} | ${e.expected_status} |`).join('\n')
    : '| - | - | - | - |';

  return `# ${projectName}

> API Testing project generated by [pom-app](https://github.com/pom-app)

## Tech Stack

- **Language**: ${info.lang}
- **HTTP Client**: ${info.client}
- **Test Runner**: ${info.runner}
- **Reporting**: Allure

## Quick Start

\`\`\`bash
cp .env.example .env  # Edit with your values
chmod +x install.sh
./install.sh
\`\`\`

## Run Tests

\`\`\`bash
${info.runCmd}
\`\`\`

## Endpoints

| Method | Path | Name | Expected Status |
|--------|------|------|----------------|
${endpointsTable}

## Docker

\`\`\`bash
docker build -t api-tests .
docker run --env-file .env api-tests
\`\`\`

## CI/CD

GitHub Actions workflow included in \`.github/workflows/tests.yml\`.
Add \`BASE_URL\` and \`API_TOKEN\` to your repository secrets.`;
}

export function getApiBaseClient(lang: string, baseUrl: string): string {
  switch (lang.toLowerCase()) {
    case 'python':
      return `"""Base API client with session management."""
import os
import requests
from dotenv import load_dotenv

load_dotenv()

BASE_URL = os.getenv("BASE_URL", "${baseUrl}")


class BaseApiClient:
    """Base client for all API interactions."""

    def __init__(self):
        self.session = requests.Session()
        self.base_url = BASE_URL.rstrip("/")
        # Set default headers
        self.session.headers.update({
            "Content-Type": "application/json",
            "Accept": "application/json",
        })
        # Add auth token if available
        token = os.getenv("API_TOKEN")
        if token:
            self.session.headers["Authorization"] = f"Bearer {token}"
        api_key = os.getenv("API_KEY")
        if api_key:
            self.session.headers["X-API-Key"] = api_key

    def _url(self, path: str) -> str:
        return f"{self.base_url}{path}"

    def get(self, path: str, **kwargs) -> requests.Response:
        return self.session.get(self._url(path), **kwargs)

    def post(self, path: str, **kwargs) -> requests.Response:
        return self.session.post(self._url(path), **kwargs)

    def put(self, path: str, **kwargs) -> requests.Response:
        return self.session.put(self._url(path), **kwargs)

    def patch(self, path: str, **kwargs) -> requests.Response:
        return self.session.patch(self._url(path), **kwargs)

    def delete(self, path: str, **kwargs) -> requests.Response:
        return self.session.delete(self._url(path), **kwargs)

    def close(self):
        self.session.close()`;

    case 'java':
      return `package api;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;

import java.io.FileInputStream;
import java.util.Properties;

/**
 * Base client for all API interactions.
 */
public class BaseApiClient {

    protected final String baseUrl;
    protected final RequestSpecification requestSpec;

    public BaseApiClient() {
        Properties props = loadEnv();
        this.baseUrl = props.getProperty("BASE_URL", "${baseUrl}");
        String token = props.getProperty("API_TOKEN", "");
        String apiKey = props.getProperty("API_KEY", "");

        RestAssured.baseURI = baseUrl;

        requestSpec = RestAssured.given()
                .header("Content-Type", "application/json")
                .header("Accept", "application/json");

        if (!token.isEmpty()) {
            requestSpec.header("Authorization", "Bearer " + token);
        }
        if (!apiKey.isEmpty()) {
            requestSpec.header("X-API-Key", apiKey);
        }
    }

    protected Response get(String path) {
        return requestSpec.get(path);
    }

    protected Response post(String path, Object body) {
        return requestSpec.body(body).post(path);
    }

    protected Response put(String path, Object body) {
        return requestSpec.body(body).put(path);
    }

    protected Response patch(String path, Object body) {
        return requestSpec.body(body).patch(path);
    }

    protected Response delete(String path) {
        return requestSpec.delete(path);
    }

    private Properties loadEnv() {
        Properties props = new Properties();
        System.getenv().forEach(props::setProperty);
        try (FileInputStream fis = new FileInputStream(".env")) {
            props.load(fis);
        } catch (Exception ignored) {
        }
        return props;
    }
}`;

    default:
      return '';
  }
}

export function getApiGitignore(lang: string): string {
  switch (lang.toLowerCase()) {
    case 'python':
      return `__pycache__/
*.py[cod]
venv/
.venv/
.pytest_cache/
.env
.env.local
allure-results/
allure-report/
htmlcov/
.coverage
.idea/
.vscode/`;

    case 'java':
      return `target/
*.class
*.jar
*.iml
.idea/
.vscode/
.settings/
.project
.classpath
.env
.env.local
allure-results/
allure-report/`;

    default:
      return `.env
.env.local
.idea/
.vscode/
allure-results/
allure-report/`;
  }
}

export function getApiDockerfile(lang: string): string {
  switch (lang.toLowerCase()) {
    case 'python':
      return `FROM python:3.12-slim

WORKDIR /tests
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["pytest", "--alluredir=allure-results"]`;

    case 'java':
      return `FROM maven:3.9-eclipse-temurin-17

WORKDIR /tests
COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY . .

CMD ["mvn", "test"]`;

    default:
      return '';
  }
}

export function getApiCiWorkflow(lang: string, projectName: string): string {
  switch (lang.toLowerCase()) {
    case 'python':
      return `name: ${projectName} API Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest --alluredir=allure-results
        env:
          BASE_URL: \${{ secrets.BASE_URL }}
          API_TOKEN: \${{ secrets.API_TOKEN }}
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
          retention-days: 30`;

    case 'java':
      return `name: ${projectName} API Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Run tests
        run: mvn test
        env:
          BASE_URL: \${{ secrets.BASE_URL }}
          API_TOKEN: \${{ secrets.API_TOKEN }}
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results/
          retention-days: 30`;

    default:
      return '';
  }
}

export function getApiEnvExample(baseUrl: string): string {
  return `# API Base URL
BASE_URL=${baseUrl}

# Authentication (if required)
API_TOKEN=
API_KEY=`;
}

export function getApiConftest(lang: string): string {
  switch (lang.toLowerCase()) {
    case 'python':
      return `"""Pytest fixtures for API testing."""
import pytest
from api.base_client import BaseApiClient


@pytest.fixture(scope="session")
def api_client():
    """Shared API client for the test session."""
    client = BaseApiClient()
    yield client
    client.close()`;

    case 'java':
      return `package base;

import io.restassured.RestAssured;
import io.restassured.specification.RequestSpecification;
import org.testng.annotations.BeforeClass;

import java.io.FileInputStream;
import java.util.Properties;

/**
 * Base class for all API tests.
 */
public class BaseApiTest {

    protected RequestSpecification requestSpec;

    @BeforeClass(alwaysRun = true)
    public void setupBase() {
        Properties props = loadEnv();
        String baseUrl = props.getProperty("BASE_URL", "");
        String token = props.getProperty("API_TOKEN", "");
        String apiKey = props.getProperty("API_KEY", "");

        RestAssured.baseURI = baseUrl;

        requestSpec = RestAssured.given()
                .header("Content-Type", "application/json")
                .header("Accept", "application/json");

        if (!token.isEmpty()) {
            requestSpec.header("Authorization", "Bearer " + token);
        }
        if (!apiKey.isEmpty()) {
            requestSpec.header("X-API-Key", apiKey);
        }
    }

    private Properties loadEnv() {
        Properties props = new Properties();
        System.getenv().forEach(props::setProperty);
        try (FileInputStream fis = new FileInputStream(".env")) {
            props.load(fis);
        } catch (Exception ignored) {
        }
        return props;
    }
}`;

    default:
      return '';
  }
}

export function getBddHooksPreview(lang: string): string {
  switch (lang.toLowerCase()) {
    case 'python':
      return `from playwright.sync_api import sync_playwright


def before_all(context):
    context.playwright = sync_playwright().start()
    context.browser = context.playwright.chromium.launch(headless=True)


def before_scenario(context, scenario):
    context.page = context.browser.new_page()
    context.base_url = os.environ.get("BASE_URL", "http://localhost")


def after_scenario(context, scenario):
    if context.page:
        context.page.close()


def after_all(context):
    context.browser.close()
    context.playwright.stop()`;

    case 'java':
      return `import io.cucumber.java.Before;
import io.cucumber.java.After;
import com.microsoft.playwright.*;

public class Hooks {
    private static Playwright playwright;
    private static Browser browser;
    private BrowserContext context;
    private Page page;

    @Before
    public void setUp() {
        playwright = Playwright.create();
        browser = playwright.chromium()
            .launch(new BrowserType.LaunchOptions().setHeadless(true));
        context = browser.newContext();
        page = context.newPage();
    }

    @After
    public void tearDown() {
        if (page != null) page.close();
        if (context != null) context.close();
        if (browser != null) browser.close();
        if (playwright != null) playwright.close();
    }
}`;

    default:
      return '';
  }
}
