import { PageElement } from '../types';

interface ExtractionResult {
  title: string;
  elements: PageElement[];
}

/**
 * Extracts interactive elements from raw HTML using DOMParser.
 * This is the same logic as extractionJS in extractor_service.go,
 * ported to run client-side for manual HTML extraction.
 */
export function extractFromHTML(html: string): ExtractionResult {
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');

  const title = doc.title || 'Untitled Page';

  const interactable = 'input, button, a, select, textarea, [role="button"], [onclick]';
  const allEls = Array.from(doc.querySelectorAll(interactable)).filter(
    el => !el.closest('[aria-hidden="true"]')
  );

  function countMatches(sel: string): number {
    try { return doc.querySelectorAll(sel).length; }
    catch { return 999; }
  }

  function esc(v: string): string {
    return v.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  }

  function isUnique(sel: string): boolean {
    return countMatches(sel) === 1;
  }

  // Verify XPath selector matches exactly 1 element in the DOM
  function isUniqueXPath(xpath: string): boolean {
    try {
      const result = doc.evaluate(xpath, doc, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);
      return result.snapshotLength === 1;
    } catch { return false; }
  }

  // Detect autogenerated IDs (MUI, React, Angular, etc.)
  function isAutoId(id: string): boolean {
    if (!id) return true;
    // MUI: _r_1e_, :r1e:, :ra:, mui-xxx
    if (/^[_:]r[_:]?\w{1,5}[_:]?$/.test(id)) return true;
    if (/^:r[a-z0-9]+:$/i.test(id)) return true;
    if (/^mui-/i.test(id)) return true;
    // React: react-select-xxx, rc_xxx
    if (/^react-/i.test(id) || /^rc[-_]/i.test(id)) return true;
    // Angular: mat-input-0, cdk-xxx
    if (/^mat-/.test(id) || /^cdk-/.test(id)) return true;
    // Generic: only hex/digits (uuid-like), short random tokens
    if (/^[0-9a-f]{8,}$/i.test(id)) return true;
    if (/^[0-9a-f-]{20,}$/i.test(id)) return true;
    return false;
  }

  // Extract semantic text from a label, ignoring decorators (MUI asterisks, icons, etc.)
  function getSemanticText(labelEl: Element): string {
    const parts: string[] = [];
    for (let i = 0; i < labelEl.childNodes.length; i++) {
      const node = labelEl.childNodes[i];
      if (node.nodeType === Node.TEXT_NODE) {
        parts.push(node.textContent || '');
      } else if (node.nodeType === Node.ELEMENT_NODE) {
        const child = node as Element;
        if (child.getAttribute('aria-hidden') === 'true') continue;
        const cls = (child.className || '').toString();
        if (/asterisk|required|star/i.test(cls)) continue;
        const tn = child.tagName.toLowerCase();
        if (tn === 'svg' || tn === 'img') continue;
        parts.push(child.textContent || '');
      }
    }
    return parts.join('').trim();
  }

  // Find the label element associated with a form element
  // Returns {el, method} where method indicates the DOM relationship found
  function findLabelElement(el: Element): { el: Element; method: string } | null {
    if (el.id) {
      const label = doc.querySelector('label[for="' + CSS.escape(el.id) + '"]');
      if (label) return { el: label, method: 'for' };
    }
    const labelledBy = el.getAttribute('aria-labelledby');
    if (labelledBy) {
      const labelEl = doc.getElementById(labelledBy);
      if (labelEl) return { el: labelEl, method: 'aria' };
    }
    const parentLabel = el.closest('label');
    if (parentLabel) return { el: parentLabel, method: 'wrapping' };
    const fieldset = el.closest('fieldset');
    if (fieldset) {
      const legend = fieldset.querySelector('legend');
      if (legend) return { el: legend, method: 'fieldset' };
    }
    // Sibling label: <div><label>Text</label><input></div>
    const parent = el.parentElement;
    if (parent) {
      const labels = parent.querySelectorAll(':scope > label');
      if (labels.length === 1) return { el: labels[0], method: 'sibling' };
    }
    return null;
  }

  // Find label text associated with a form element
  // Returns {clean, raw, method}: clean = semantic text (for naming), raw = full textContent, method = DOM relationship
  function findLabelText(el: Element): { clean: string; raw: string; method: string } {
    const result = findLabelElement(el);
    if (!result) {
      const ariaLabel = el.getAttribute('aria-label');
      if (ariaLabel) return { clean: ariaLabel.trim(), raw: ariaLabel.trim(), method: 'aria-attr' };
      return { clean: '', raw: '', method: '' };
    }
    const raw = (result.el.textContent || '').replace(/\s+/g, ' ').trim();
    const clean = getSemanticText(result.el);
    return { clean, raw, method: result.method };
  }

  function buildSelector(el: Element): string {
    const tag = el.tagName.toLowerCase();
    const htmlEl = el as HTMLElement;
    const inputEl = el as HTMLInputElement;
    const isFormEl = tag === 'input' || tag === 'select' || tag === 'textarea';

    // 1. #id — only if not autogenerated
    if (el.id && !isAutoId(el.id)) {
      const sel = '#' + CSS.escape(el.id);
      if (isUnique(sel)) return sel;
    }

    // 2. tag[name='value']
    if (inputEl.name) {
      const sel = tag + "[name='" + esc(inputEl.name) + "']";
      if (isUnique(sel)) return sel;
    }

    // 3. tag[placeholder='value']
    if (inputEl.placeholder) {
      const sel = tag + "[placeholder='" + esc(inputEl.placeholder) + "']";
      if (isUnique(sel)) return sel;
    }

    // 4. input[type='value']
    if (tag === 'input' && inputEl.type) {
      const sel = "input[type='" + esc(inputEl.type) + "']";
      if (isUnique(sel)) return sel;
    }

    // 5. tag[type='value'][name='value']
    if (inputEl.type && inputEl.name) {
      const sel = tag + "[type='" + esc(inputEl.type) + "'][name='" + esc(inputEl.name) + "']";
      if (isUnique(sel)) return sel;
    }

    // 6. tag[type='value'][placeholder='value']
    if (inputEl.type && inputEl.placeholder) {
      const sel = tag + "[type='" + esc(inputEl.type) + "'][placeholder='" + esc(inputEl.placeholder) + "']";
      if (isUnique(sel)) return sel;
    }

    // 7. a[href='value']
    if (tag === 'a') {
      const href = el.getAttribute('href');
      if (href && href !== '#' && href !== '') {
        const sel = "a[href='" + esc(href) + "']";
        if (isUnique(sel)) return sel;
      }
    }

    // 8. tag[aria-label='value']
    const ariaLabel = el.getAttribute('aria-label');
    if (ariaLabel) {
      const sel = tag + "[aria-label='" + esc(ariaLabel) + "']";
      if (isUnique(sel)) return sel;
    }

    // 9. data-testid, data-test, data-cy, data-qa
    const testAttrs = ['data-testid', 'data-test', 'data-cy', 'data-qa'];
    for (const attr of testAttrs) {
      const val = el.getAttribute(attr);
      if (val) {
        const sel = "[" + attr + "='" + esc(val) + "']";
        if (isUnique(sel)) return sel;
      }
    }

    // 10. tag[title='value']
    if (htmlEl.title) {
      const sel = tag + "[title='" + esc(htmlEl.title) + "']";
      if (isUnique(sel)) return sel;
    }

    // 11. Label-based selector for form elements (XPath with associated label text)
    if (isFormEl) {
      const labelResult = findLabelText(el);
      if (labelResult.clean && labelResult.clean.length <= 60) {
        const lt = esc(labelResult.clean);
        let xpathCandidate = '';
        if (labelResult.method === 'for') {
          xpathCandidate = "//" + tag + "[@id=//label[contains(normalize-space(.),'" + lt + "')]/@for]";
        } else if (labelResult.method === 'wrapping') {
          xpathCandidate = "//label[contains(normalize-space(.),'" + lt + "')]//" + tag;
        } else if (labelResult.method === 'fieldset') {
          xpathCandidate = "//fieldset[.//legend[contains(normalize-space(.),'" + lt + "')]]//" + tag;
        } else if (labelResult.method === 'sibling') {
          xpathCandidate = "//*[label[contains(normalize-space(.),'" + lt + "')]]/" + tag;
        }
        if (xpathCandidate && isUniqueXPath(xpathCandidate)) {
          return "xpath=" + xpathCandidate;
        }
      }
    }

    // 12. XPath with visible text (unique) — buttons, links, divs with role
    const text = (htmlEl.innerText || el.textContent || '').trim();
    if (text && text.length > 0 && text.length <= 60) {
      // 12a. If element has role, use tag[@role][normalize-space(.)='text'] (very specific)
      const role = el.getAttribute('role');
      if (role) {
        return "xpath=//" + tag + "[@role='" + esc(role) + "'][normalize-space(.)='" + esc(text) + "']";
      }

      // 12b. Original: count same tag with same text, if unique use normalize-space(.)
      const sameTagEls = doc.querySelectorAll(tag);
      let textCount = 0;
      for (const other of Array.from(sameTagEls)) {
        if (((other as HTMLElement).innerText || other.textContent || '').trim() === text) textCount++;
      }
      if (textCount === 1) {
        return "xpath=//" + tag + "[normalize-space(.)='" + esc(text) + "']";
      }

      // 12c. If count > 1, try direct text node match (distinguishes parent from leaf)
      let directCount = 0;
      for (const other of Array.from(sameTagEls)) {
        const directText = Array.from(other.childNodes)
          .filter((n: ChildNode) => n.nodeType === Node.TEXT_NODE)
          .map((n: ChildNode) => n.textContent || '')
          .join('')
          .trim();
        if (directText === text) directCount++;
      }
      if (directCount === 1) {
        return "xpath=//" + tag + "[normalize-space(text())='" + esc(text) + "']";
      }

      // 12d. Child element text match — handles <button><span>Text</span></button>
      let childTextCount = 0;
      for (const other of Array.from(sameTagEls)) {
        for (const child of Array.from(other.children)) {
          if (((child as HTMLElement).innerText || child.textContent || '').trim() === text) {
            childTextCount++;
            break;
          }
        }
      }
      if (childTextCount >= 1) {
        return "xpath=//" + tag + "[*[normalize-space(.)='" + esc(text) + "']]";
      }
    }

    // 13. tag.class1.class2 — skip framework-generated classes (css-xxx, Mui-xxx)
    if (el.className && typeof el.className === 'string') {
      const classes = el.className.trim().split(/\s+/)
        .filter(c => c.length > 0 && !/^css-/.test(c) && !/^Mui/.test(c) && !/^jss\d/.test(c))
        .slice(0, 3);
      if (classes.length > 0) {
        const sel = tag + classes.map(c => '.' + CSS.escape(c)).join('');
        if (isUnique(sel)) return sel;
      }
    }

    // 14. #parentId > tag:nth-of-type(n) — skip autogenerated parent IDs
    let parent = el.parentElement;
    let depth = 0;
    while (parent && parent !== doc.body && depth < 5) {
      if (parent.id && !isAutoId(parent.id)) {
        let pos = 0;
        for (const child of Array.from(parent.querySelectorAll(':scope > ' + tag))) {
          pos++;
          if (child === el) {
            const sel = '#' + CSS.escape(parent.id) + ' > ' + tag + ':nth-of-type(' + pos + ')';
            if (isUnique(sel)) return sel;
          }
        }
        pos = 0;
        const descendants = parent.querySelectorAll(tag);
        for (let i = 0; i < descendants.length; i++) {
          if (descendants[i] === el) {
            const sel = '#' + CSS.escape(parent.id) + ' ' + tag + ':nth-of-type(' + (i + 1) + ')';
            if (isUnique(sel)) return sel;
            break;
          }
        }
        break;
      }
      parent = parent.parentElement;
      depth++;
    }

    // Fallback (non-unique)
    if (el.id && !isAutoId(el.id)) return '#' + CSS.escape(el.id);
    if (inputEl.name) return tag + "[name='" + esc(inputEl.name) + "']";
    if (tag === 'input' && inputEl.type) return "input[type='" + esc(inputEl.type) + "']";
    return tag;
  }

  // Resolve human-readable label for any element
  function resolveLabel(el: Element): string {
    const htmlEl = el as HTMLElement;
    const tag = el.tagName.toLowerCase();

    // For buttons/links, innerText is fine
    if (tag === 'button' || tag === 'a') {
      return (htmlEl.innerText || el.textContent || '').trim().substring(0, 100);
    }

    // For form elements, use findLabelText (shared with buildSelector)
    if (tag === 'input' || tag === 'select' || tag === 'textarea') {
      const result = findLabelText(el);
      if (result.clean) return result.clean;
      if ((el as HTMLInputElement).placeholder) return (el as HTMLInputElement).placeholder;
    }

    return (htmlEl.innerText || el.textContent || '').trim().substring(0, 100);
  }

  const elements: PageElement[] = Array.from(allEls).map(el => {
    const inputEl = el as HTMLInputElement;
    return {
      tag: el.tagName.toLowerCase(),
      type: inputEl.type || '',
      id: el.id || '',
      name: inputEl.name || '',
      class: (typeof el.className === 'string' ? el.className : '') || '',
      placeholder: inputEl.placeholder || '',
      text: resolveLabel(el),
      href: (el as HTMLAnchorElement).href || '',
      selector: buildSelector(el),
    };
  }).filter(el => {
    if (el.tag === 'a' && !el.text && !el.href) return false;
    if (el.type === 'hidden') return false;
    return true;
  });

  return { title, elements };
}
